# Generated by Django 3.2 on 2021-04-29 14:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identified', models.CharField(default='WRET7', max_length=5)),
                ('tranzaction', models.CharField(blank=True, choices=[('1', 'Inchiriere'), ('2', 'Vanzare')], max_length=10)),
                ('types', models.CharField(choices=[('1', 'Garsoniera'), ('2', 'Apartament'), ('3', 'Casa'), ('4', 'Teren')], max_length=50)),
                ('title', models.CharField(max_length=3000)),
                ('description', models.TextField(max_length=20000)),
                ('year', models.CharField(blank=True, choices=[('1', 'Inainte de 1977'), ('2', '1977 - 1990'), ('3', '1990 - 2000'), ('4', 'Dupa 2000')], max_length=50)),
                ('subdivision', models.CharField(blank=True, choices=[('1', 'Decomandat'), ('2', 'Semidecomandat'), ('3', 'Circular')], max_length=100)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('surface', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(db_index=True)),
                ('negociable', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, choices=[('1', 'EURO'), ('2', 'RON')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('district', models.IntegerField(blank=True, null=True)),
                ('photo_main', models.ImageField(upload_to='static/admin/img/listing_photo')),
                ('photo_1', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('photo_2', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('photo_3', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('photo_4', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('photo_5', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('photo_6', models.ImageField(blank=True, upload_to='static/admin/img/listing_photo')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SendProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nume si Prenume')),
                ('email', models.EmailField(error_messages={'required': 'Va rugam sa introduceti adresa de email.'}, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='e-mail')),
                ('phone', models.CharField(max_length=15, verbose_name='telefon')),
                ('types', models.CharField(choices=[('1', 'Garsoniera'), ('2', 'Apartament'), ('3', 'Casa'), ('4', 'Teren')], max_length=20, verbose_name='Tip proprietate')),
                ('price', models.CharField(max_length=20, verbose_name='Pret')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('photo_main', models.ImageField(upload_to='', verbose_name='Poza 1')),
                ('photo_1', models.ImageField(blank=True, upload_to='', verbose_name='Poza 2')),
                ('photo_2', models.ImageField(blank=True, upload_to='', verbose_name='Poza 3')),
                ('photo_3', models.ImageField(blank=True, upload_to='', verbose_name='Poza 4')),
                ('photo_4', models.ImageField(blank=True, upload_to='', verbose_name='Poza 5')),
                ('photo_5', models.ImageField(blank=True, upload_to='', verbose_name='Poza 6')),
                ('photo_6', models.ImageField(blank=True, upload_to='', verbose_name='Poza 7')),
            ],
        ),
    ]
