# Generated by Django 3.2 on 2021-04-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendProperty',
        ),
        migrations.AlterField(
            model_name='listing',
            name='identified',
            field=models.CharField(default='G3DV5', max_length=5),
        ),
    ]
