# Generated by Django 3.1.7 on 2021-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210430_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tranzaction',
            new_name='transaction',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='identified',
        ),
        migrations.AddField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='RSOQD', max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, choices=[('1', '€'), ('2', 'RON')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
