# Generated by Django 3.1.7 on 2021-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210504_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='DXMQV', max_length=5),
        ),
    ]
