# Generated by Django 3.1.7 on 2021-05-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20210506_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='transaction',
            new_name='transactions',
        ),
        migrations.AlterField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='F63KM', max_length=5),
        ),
    ]
