# Generated by Django 3.1.7 on 2021-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210527_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
        migrations.AlterField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='YGU00', max_length=5),
        ),
    ]
