# Generated by Django 3.1.7 on 2021-05-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210527_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, choices=[('1', 'Sector 1'), ('2', 'Sector 2'), ('3', 'Sector 3'), ('4', 'Sector 4'), ('5', 'Sector 5'), ('6', 'Sector 6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='identifier',
            field=models.CharField(default='3FHI2', max_length=5),
        ),
    ]
